module.exports = {
	"fa-500px": ["500px"],
	"fa-adjust": ["对比度"],
	"fa-adn": [],
	"fa-align-center": ["居中对齐"],
	"fa-align-justify": ["两端对齐"],
	"fa-align-left": ["左对齐"],
	"fa-align-right": ["右对齐"],
	"fa-amazon": ["亚马逊"],
	"fa-ambulance": ["救护车", "紧急", "医院", "紧急电话"],
	"fa-anchor": ["锚"],
	"fa-android": ["android", "机器人", "智能手机", "APK"],
	"fa-angellist": [],
	"fa-angle-double-down": [],
	"fa-angle-double-left": [],
	"fa-angle-double-right": [],
	"fa-angle-double-up": [],
	"fa-angle-down": [],
	"fa-angle-left": [],
	"fa-angle-right": [],
	"fa-angle-up": [],
	"fa-apple": ["苹果", "IOS"],
	"fa-archive": ["箱子", "归档", "文件", "储藏"],
	"fa-area-chart": ["图表", "折线图"],
	"fa-arrow-circle-down": [],
	"fa-arrow-circle-left": [],
	"fa-arrow-circle-o-down": [],
	"fa-arrow-circle-o-left": [],
	"fa-arrow-circle-o-right": [],
	"fa-arrow-circle-o-up": [],
	"fa-arrow-circle-right": [],
	"fa-arrow-circle-up": [],
	"fa-arrow-down": [],
	"fa-arrow-left": [],
	"fa-arrow-right": [],
	"fa-arrow-up": [],
	"fa-arrows": ["移动", "箭头"],
	"fa-arrows-alt": ["全屏", "缩放", "最大化", "箭头"],
	"fa-arrows-h": ["水平拉伸"],
	"fa-arrows-v": ["纵向拉伸"],
	"fa-asterisk": [],
	"fa-at": ["邮箱", "@"],
	"fa-automobile": "fa-car",
	"fa-backward": [],
	"fa-balance-scale": [],
	"fa-ban": ["禁止", "错误", "无效"],
	"fa-bank": ["银行", "法院"],
	"fa-bar-chart": ["图表", "条形图", "柱状图"],
	"fa-bar-chart-o": "fa-bar-chart",
	"fa-barcode": ["条形码"],
	"fa-bars": [],
	"fa-battery-0": ["电池", "电量", "无电量"],
	"fa-battery-1": ["电池", "电量", "一格电量"],
	"fa-battery-2": ["电池", "电量", "两格电量"],
	"fa-battery-3": ["电池", "电量", "三格电量"],
	"fa-battery-4": ["电池", "电量", "电量满格"],
	"fa-battery-empty": "fa-battery-0",
	"fa-battery-full": "fa-battery-4",
	"fa-battery-half": "fa-battery-2",
	"fa-battery-quarter": "fa-battery-1",
	"fa-battery-three-quarters": "fa-battery-3",
	"fa-bed": ["床", "睡觉", "休息"],
	"fa-beer": ["啤酒", "杯子"],
	"fa-behance": [],
	"fa-behance-square": [],
	"fa-bell": ["铃铛","消息","提醒","闹钟"],
	"fa-bell-o": ["铃铛","消息","提醒","闹钟"],
	"fa-bell-slash": ["静音","铃铛"],
	"fa-bell-slash-o": ["静音","铃铛"],
	"fa-bicycle": ["自行车"],
	"fa-binoculars": ["望远镜", "查找"],
	"fa-birthday-cake": [],
	"fa-bitbucket": [],
	"fa-bitbucket-square": [],
	"fa-bitcoin": ["比特币","钱","货币"],
	"fa-black-tie": ["领带"],
	"fa-bold": ["粗体", "加粗"],
	"fa-bolt": ["闪电", "迅速"],
	"fa-bomb": ["炸弹", "危险", "爆炸"],
	"fa-book": ["书本", "文档", "参考", "学习"],
	"fa-bookmark": ["书签","标志"],
	"fa-bookmark-o": ["书签","标志"],
	"fa-briefcase": ["工具箱"],
	"fa-btc": ["比特币","钱","货币"],
	"fa-bug": ["BUG", "漏洞", "反馈"],
	"fa-building": [],
	"fa-building-o": [],
	"fa-bullhorn": ["公告", "小喇叭", "消息"],
	"fa-bullseye": [],
	"fa-bus": [],
	"fa-buysellads": [],
	"fa-cab": [],
	"fa-calculator": ["计算器", "计费", "消费"],
	"fa-calendar": ["日历", "日期", "计划", "日程"],
	"fa-calendar-check-o": [],
	"fa-calendar-minus-o": [],
	"fa-calendar-o": [],
	"fa-calendar-plus-o": [],
	"fa-calendar-times-o": [],
	"fa-camera": ["照相机", "拍照", "照片"],
	"fa-camera-retro": "fa-camera",
	"fa-car": [],
	"fa-caret-down": [],
	"fa-caret-left": [],
	"fa-caret-right": [],
	"fa-caret-square-o-down": [],
	"fa-caret-square-o-left": [],
	"fa-caret-square-o-right": [],
	"fa-caret-square-o-up": [],
	"fa-caret-up": [],
	"fa-cart-arrow-down": [],
	"fa-cart-plus": ["添加购物车"],
	"fa-cc": ["信用卡"],
	"fa-cc-amex": ["银行卡", "信用卡"],
	"fa-cc-diners-club": ["银行卡", "信用卡"],
	"fa-cc-discover": ["银行卡", "信用卡"],
	"fa-cc-jcb": ["银行卡", "信用卡"],
	"fa-cc-mastercard": ["银行卡", "信用卡"],
	"fa-cc-paypal": ["Paypal", "支付"],
	"fa-cc-stripe": ["银行卡", "信用卡"],
	"fa-cc-visa": ["银行卡", "信用卡"],
	"fa-certificate": [],
	"fa-chain": ["链接", "超链接"],
	"fa-chain-broken": ["断开", "链接断开", "无效链接"],
	"fa-check": ["确定","勾选","对勾","正确"],
	"fa-check-circle": ["确定","勾选","对勾","正确"],
	"fa-check-circle-o": ["确定","勾选","对勾","正确"],
	"fa-check-square": [],
	"fa-check-square-o": [],
	"fa-chevron-circle-down": [],
	"fa-chevron-circle-left": [],
	"fa-chevron-circle-right": [],
	"fa-chevron-circle-up": [],
	"fa-chevron-down": [],
	"fa-chevron-left": [],
	"fa-chevron-right": [],
	"fa-chevron-up": [],
	"fa-child": [],
	"fa-chrome": ["Chrome","浏览器"],
	"fa-circle": [],
	"fa-circle-o": [],
	"fa-circle-o-notch": [],
	"fa-circle-thin": [],
	"fa-clipboard": ["剪切板"],
	"fa-clock-o": ["时钟","时间","闹钟"],
	"fa-clone": ["复制","克隆","层"],
	"fa-close": ["关闭","删除","错误","交叉"],
	"fa-cloud": ["云","网盘"],
	"fa-cloud-download": ["云","下载"],
	"fa-cloud-upload": ["云","上传"],
	"fa-cny": ["货币", "人民币", "钱"],
	"fa-code": ["代码"],
	"fa-code-fork": [],
	"fa-codepen": [],
	"fa-coffee": ["杯子", "咖啡", "休息"],
	"fa-cog": ["配置", "设置", "首选项"],
	"fa-cogs": "fa-cog",
	"fa-columns": [],
	"fa-comment": ["对话", "聊天", "气泡"],
	"fa-comment-o": "fa-comment",
	"fa-commenting": ["聊天","消息","留言","通知"],
	"fa-commenting-o": "fa-commenting",
	"fa-comments": [],
	"fa-comments-o": [],
	"fa-compass": [],
	"fa-compress": ["压缩", "缩放", "缩小"],
	"fa-connectdevelop": [],
	"fa-contao": [],
	"fa-copy": ["复制"],
	"fa-copyright": ["版权"],
	"fa-creative-commons": ["CC协议","开源协议"],
	"fa-credit-card": ["银行卡","信用卡"],
	"fa-crop": ["裁剪","切割"],
	"fa-crosshairs": ["准星", "瞄准"],
	"fa-css3": [],
	"fa-cube": ["方块", "实体"],
	"fa-cubes": "fa-cube",
	"fa-cut": ["剪刀", "剪切"],
	"fa-cutlery": ["餐具","饮食"],
	"fa-dashboard": ["控制台", "仪表盘"],
	"fa-dashcube": [],
	"fa-database": ["数据库"],
	"fa-dedent": ["缩进"],
	"fa-delicious": [],
	"fa-desktop": ["显示器", "电脑", "台式机"],
	"fa-deviantart": [],
	"fa-diamond": ["钻石"],
	"fa-digg": [],
	"fa-dollar": ["美元", "钱"],
	"fa-dot-circle-o": [],
	"fa-download": ["下载"],
	"fa-dribbble": [],
	"fa-dropbox": [],
	"fa-drupal": [],
	"fa-edit": "fa-pencil-square-o",
	"fa-eject": [],
	"fa-ellipsis-h": ["省略号"],
	"fa-ellipsis-v": ["省略号", "菜单切换按钮"],
	"fa-empire": [],
	"fa-envelope": ["信封","邮件","信件"],
	"fa-envelope-o": ["信封","邮件","信件"],
	"fa-envelope-square": ["信封","邮件","信件"],
	"fa-eraser": ["橡皮", "擦除"],
	"fa-eur": ["欧元", "钱", "货币", "货币符号"],
	"fa-euro": "fa-eur",
	"fa-exchange": [],
	"fa-exclamation": ["叹号", "警告", "提示"],
	"fa-exclamation-circle": ["错误", "警告", "提示"],
	"fa-exclamation-triangle": ["危险", "警告", "提示"],
	"fa-expand": ["放大", "展开"],
	"fa-expeditedssl": ["SSL"],
	"fa-external-link": ["链接", "新窗口打开", "弹出"],
	"fa-external-link-square": [],
	"fa-eye": ["眼镜","看","可视","显示"],
	"fa-eye-slash": ["隐藏","不可视"],
	"fa-eyedropper": ["取色器","滴管"],
	"fa-facebook": ["facebook", "脸书"],
	"fa-facebook-f": "fa-facebook",
	"fa-facebook-official": "fa-facebook",
	"fa-facebook-square": "fa-facebook",
	"fa-fast-backward": ["返回", "播放控制", "回退"],
	"fa-fast-forward": ["快进", "播放控制"],
	"fa-fax": ["传真机","电话"],
	"fa-feed": ["信号", "广播"],
	"fa-female": ["女性","裙子"],
	"fa-fighter-jet": ["战斗机","分集"],
	"fa-file": ["文件", "文件类型"],
	"fa-file-archive-o": ["文件", "文件类型", "压缩包"],
	"fa-file-audio-o": ["文件", "文件类型", "音频", "音乐"],
	"fa-file-code-o": ["文件", "文件类型", "代码", "源码"],
	"fa-file-excel-o": ["文件", "文件类型", "EXCEL", "表格"],
	"fa-file-image-o": ["文件", "文件类型", "图像", "照片", "图片"],
	"fa-file-movie-o": "fa-file-video-o",
	"fa-file-o": ["文件", "文件类型"],
	"fa-file-pdf-o": ["文件", "文件类型", "PDF", "文档"],
	"fa-file-photo-o": "fa-file-image-o",
	"fa-file-picture-o": "fa-file-image-o",
	"fa-file-powerpoint-o": ["文件", "文件类型", "PPT", "演示文档"],
	"fa-file-sound-o": "fa-file-audio-o",
	"fa-file-text": ["文件", "文件类型", "文档"],
	"fa-file-text-o": ["文件", "文件类型", "文档"],
	"fa-file-video-o": ["文件", "文件类型", "视频", "电影"],
	"fa-file-word-o": ["文件", "文件类型", "WORD", "文档"],
	"fa-file-zip-o": "fa-file-archive-o",
	"fa-files-o": ["文件", "复制"],
	"fa-film": ["电影", "视频"],
	"fa-filter": ["过滤","漏斗","筛选"],
	"fa-fire": [],
	"fa-fire-extinguisher": [],
	"fa-firefox": ["浏览器", "火狐", "FireFox"],
	"fa-flag": ["旗帜","标记","旗子"],
	"fa-flag-checkered": [],
	"fa-flag-o": "fa-flag",
	"fa-flash": [],
	"fa-flask": ["实验性", "化学", "测试功能"],
	"fa-flickr": [],
	"fa-floppy-o": ["保存","软盘"],
	"fa-folder": ["文件夹"],
	"fa-folder-o": "fa-folder",
	"fa-folder-open": ["文件夹","档案","打开"],
	"fa-folder-open-o": ["文件夹","档案","打开"],
	"fa-font": ["字体"],
	"fa-fonticons": [],
	"fa-forumbee": [],
	"fa-forward": ["快进"],
	"fa-foursquare": [],
	"fa-frown-o": [],
	"fa-futbol-o": "fa-soccer-ball-o",
	"fa-gamepad": [],
	"fa-gavel": "fa-legal",
	"fa-gbp": [],
	"fa-ge": [],
	"fa-gear": ["齿轮","设置","个性化"],
	"fa-gears": ["齿轮","设置","个性化"],
	"fa-genderless": [],
	"fa-get-pocket": [],
	"fa-gg": [],
	"fa-gg-circle": [],
	"fa-gift": ["礼物","赠送"],
	"fa-git": [],
	"fa-git-square": [],
	"fa-github": [],
	"fa-github-alt": [],
	"fa-github-square": [],
	"fa-gittip": [],
	"fa-glass": ["酒杯","饮料","杯子"],
	"fa-globe": ["全球","地球","翻译","国际化"],
	"fa-google": [],
	"fa-google-plus": [],
	"fa-google-plus-square": [],
	"fa-google-wallet": [],
	"fa-graduation-cap": ["毕业","博士帽","学历","学业"],
	"fa-gratipay": [],
	"fa-group": ["群组", "用户"],
	"fa-hacker-news": [],
	"fa-hand-grab-o": [],
	"fa-hand-lizard-o": [],
	"fa-hand-o-down": [],
	"fa-hand-o-left": [],
	"fa-hand-o-right": [],
	"fa-hand-o-up": [],
	"fa-hand-paper-o": [],
	"fa-hand-peace-o": [],
	"fa-hand-pointer-o": [],
	"fa-hand-rock-o": [],
	"fa-hand-scissors-o": [],
	"fa-hand-spock-o": [],
	"fa-hand-stop-o": [],
	"fa-hdd-o": ["硬盘", "存储"],
	"fa-header": ["标题"],
	"fa-headphones": ["耳机","音乐"],
	"fa-heart": [],
	"fa-heart-o": [],
	"fa-heartbeat": [],
	"fa-history": ["历史","恢复"],
	"fa-home": ["房子","家","主页"],
	"fa-hotel": ["床","休息","睡觉","医院"],
	"fa-hourglass": ["加载中","沙漏"],
	"fa-hourglass-1": [],
	"fa-hourglass-2": [],
	"fa-hourglass-3": [],
	"fa-hourglass-end": [],
	"fa-hourglass-half": [],
	"fa-hourglass-o": [],
	"fa-hourglass-start": [],
	"fa-houzz": [],
	"fa-html5": [],
	"fa-i-cursor": ["光标", "输入光标"],
	"fa-ils": [],
	"fa-image": ["图片"],
	"fa-inbox": ["收件箱", "盒子"],
	"fa-indent": ["缩进"],
	"fa-industry": ["工厂", "产业"],
	"fa-info": ["提示", "消息"],
	"fa-info-circle": "fa-info",
	"fa-inr": ["钱", "印度卢比"],
	"fa-instagram": [],
	"fa-institution": ["大学", "机构", "政府", "学院"],
	"fa-internet-explorer": ["IE", "浏览器"],
	"fa-intersex": [],
	"fa-ioxhost": [],
	"fa-italic": ["斜体"],
	"fa-joomla": [],
	"fa-jpy": [],
	"fa-jsfiddle": [],
	"fa-key": ["密钥", "钥匙", "加密", "密码"],
	"fa-keyboard-o": ["键盘","输入法"],
	"fa-krw": [],
	"fa-language": ["翻译","语言","国际化"],
	"fa-laptop": ["笔记本电脑"],
	"fa-lastfm": [],
	"fa-lastfm-square": [],
	"fa-leaf": ["叶子", "模板"],
	"fa-leanpub": [],
	"fa-legal": ["法律", "条款", "声明"],
	"fa-lemon-o": ["柠檬"],
	"fa-level-down": [],
	"fa-level-up": [],
	"fa-life-bouy": [],
	"fa-life-buoy": [],
	"fa-life-ring": [],
	"fa-life-saver": [],
	"fa-lightbulb-o": ["灯泡", "创意", "灵感"],
	"fa-line-chart": ["图标", "趋势"],
	"fa-link": ["链接"],
	"fa-linkedin": [],
	"fa-linkedin-square": [],
	"fa-linux": [],
	"fa-list": ["列表","菜单"],
	"fa-list-alt": [],
	"fa-list-ol": ["有序列表"],
	"fa-list-ul": ["无序列表"],
	"fa-location-arrow": [],
	"fa-lock": ["安全", "密码", "锁", "锁定"],
	"fa-long-arrow-down": [],
	"fa-long-arrow-left": [],
	"fa-long-arrow-right": [],
	"fa-long-arrow-up": [],
	"fa-magic": ["魔术棒"],
	"fa-magnet": ["磁力链", "Magnet"],
	"fa-mail-forward": ["转发"],
	"fa-mail-reply": ["回复", "返回"],
	"fa-mail-reply-all": [],
	"fa-male": ["人","男性"],
	"fa-map": ["地图"],
	"fa-map-marker": ["位置", "定位"],
	"fa-map-o": "fa-map",
	"fa-map-pin": ["图钉", "标记"],
	"fa-map-signs": ["方向牌", "导航"],
	"fa-mars": ["男性"],
	"fa-mars-double": ["GAY", "同性恋"],
	"fa-mars-stroke": [],
	"fa-mars-stroke-h": [],
	"fa-mars-stroke-v": [],
	"fa-maxcdn": [],
	"fa-meanpath": [],
	"fa-medium": [],
	"fa-meh-o": [],
	"fa-mercury": [],
	"fa-microphone": ["麦克风", "录音", "语音"],
	"fa-microphone-slash": ["关闭语音"],
	"fa-minus": ["负号","禁止","删除"],
	"fa-minus-circle": "fa-minus",
	"fa-minus-square": ["折叠", "禁止"],
	"fa-minus-square-o": "fa-minus-square",
	"fa-mobile": ["手机","电话"],
	"fa-mobile-phone": ["手机","电话"],
	"fa-money": ["钱","货币","充值"],
	"fa-moon-o": ["月亮","夜"],
	"fa-mortar-board": ["博士帽","学习","知识","毕业","学历"],
	"fa-motorcycle": ["摩托车","交通工具"],
	"fa-mouse-pointer": [],
	"fa-music": ["音乐","旋律","音效"],
	"fa-navicon": [],
	"fa-neuter": [],
	"fa-newspaper-o": ["报纸", "新闻"],
	"fa-object-group": [],
	"fa-object-ungroup": [],
	"fa-odnoklassniki": [],
	"fa-odnoklassniki-square": [],
	"fa-opencart": [],
	"fa-openid": [],
	"fa-opera": [],
	"fa-optin-monster": [],
	"fa-outdent": [],
	"fa-pagelines": [],
	"fa-paint-brush": [],
	"fa-paper-plane": ["纸飞机", "前往", "发送", "Shadowsocks"],
	"fa-paper-plane-o": "fa-paper-plane",
	"fa-paperclip": ["附件"],
	"fa-paragraph": ["段落", "分段符号"],
	"fa-paste": ["粘贴"],
	"fa-pause": ["暂停"],
	"fa-paw": ["百度","脚印"],
	"fa-paypal": ["支付", "Paypal"],
	"fa-pencil": ["编辑","铅笔","笔","修改","写字","书写"],
	"fa-pencil-square": ["编辑","铅笔","笔","修改","写字","书写"],
	"fa-pencil-square-o": ["编辑","铅笔","笔","修改","写字","书写"],
	"fa-phone": ["拨号","联系","电话","话筒"],
	"fa-phone-square": ["拨号","联系","电话","话筒"],
	"fa-photo": ["图片","照片","图像"],
	"fa-picture-o": ["图片","照片","图像"],
	"fa-pie-chart": ["统计","图表","饼图"],
	"fa-pied-piper": [],
	"fa-pied-piper-alt": [],
	"fa-pinterest": [],
	"fa-pinterest-p": [],
	"fa-pinterest-square": [],
	"fa-plane": ["飞机"],
	"fa-play": ["播放","三角形"],
	"fa-play-circle": ["播放"],
	"fa-play-circle-o": ["播放"],
	"fa-plug": ["插头", "插件"],
	"fa-plus": ["加号","添加","增加"],
	"fa-plus-circle": "fa-plus",
	"fa-plus-square": ["展开", "添加"],
	"fa-plus-square-o": "fa-plus-square",
	"fa-power-off": ["电源", "关机"],
	"fa-print": ["打印"],
	"fa-puzzle-piece": ["插件","拼图"],
	"fa-qq": [],
	"fa-qrcode": ["二维码"],
	"fa-question": ["帮助", "咨询", "关于", "疑问"],
	"fa-question-circle": "fa-question",
	"fa-quote-left": ["引用", "冒号"],
	"fa-quote-right": "fa-quote-left",
	"fa-ra": [],
	"fa-random": ["随机"],
	"fa-rebel": [],
	"fa-recycle": [],
	"fa-reddit": [],
	"fa-reddit-square": [],
	"fa-refresh": ["刷新", "重新加载", "加载"],
	"fa-registered": [],
	"fa-remove": ["删除","错误","交叉"],
	"fa-renren": [],
	"fa-reorder": ["录制","菜单","三条杠"],
	"fa-repeat": [],
	"fa-reply": ["回复","撤销","返回"],
	"fa-reply-all": [],
	"fa-retweet": [],
	"fa-rmb": "fa-cny",
	"fa-road": ["马路","轨道"],
	"fa-rocket": ["启动","火箭"],
	"fa-rotate-left": ["刷新", "旋转", "左转"],
	"fa-rotate-right": ["刷新", "旋转", "右转"],
	"fa-rouble": [],
	"fa-rss": ["RSS","广播","信号"],
	"fa-rss-square": ["RSS"],
	"fa-rub": [],
	"fa-ruble": [],
	"fa-rupee": [],
	"fa-safari": [],
	"fa-save": ["保存","存档"],
	"fa-scissors": ["剪刀","剪切"],
	"fa-search": ["搜索","查找","放大镜"],
	"fa-search-minus": ["缩小","放大镜"],
	"fa-search-plus": ["放大","放大镜"],
	"fa-sellsy": [],
	"fa-send": "fa-paper-plane",
	"fa-send-o": "fa-paper-plane",
	"fa-server": ["服务器","菜单"],
	"fa-share": ["分享","重做","恢复","继续"],
	"fa-share-alt": ["分享"],
	"fa-share-alt-square": "fa-share-alt",
	"fa-share-square": ["分享", "转发"],
	"fa-share-square-o": "fa-share-square",
	"fa-shekel": [],
	"fa-sheqel": [],
	"fa-shield": ["安全", "盾牌"],
	"fa-ship": ["船", "交通"],
	"fa-shirtsinbulk": [],
	"fa-shopping-cart": ["购物车"],
	"fa-sign-in": ["登录","进入","导入"],
	"fa-sign-out": ["登录","退出","出去","导出"],
	"fa-signal": ["信号"],
	"fa-simplybuilt": [],
	"fa-sitemap": ["树","网络","网站地图"],
	"fa-skyatlas": [],
	"fa-skype": [],
	"fa-slack": [],
	"fa-sliders": ["滑动","设置"],
	"fa-slideshare": [],
	"fa-smile-o": ["笑脸","开心"],
	"fa-soccer-ball-o": ["足球","运动"],
	"fa-sort": [],
	"fa-sort-alpha-asc": ["排序", "排序规则", "升序"],
	"fa-sort-alpha-desc": ["排序", "排序规则", "倒序"],
	"fa-sort-amount-asc": ["排序", "排序规则", "升序"],
	"fa-sort-amount-desc": ["排序", "排序规则", "倒序"],
	"fa-sort-asc": [],
	"fa-sort-desc": [],
	"fa-sort-down": [],
	"fa-sort-numeric-asc": ["排序", "排序规则", "升序"],
	"fa-sort-numeric-desc": ["排序", "排序规则", "倒序"],
	"fa-sort-up": [],
	"fa-soundcloud": [],
	"fa-space-shuttle": [],
	"fa-spinner": ["加载中", "进度条"],
	"fa-spoon": [],
	"fa-spotify": [],
	"fa-square": [],
	"fa-square-o": [],
	"fa-stack-exchange": [],
	"fa-stack-overflow": [],
	"fa-star": ["评分","黑星","星星"],
	"fa-star-half": ["评分","星星","半星"],
	"fa-star-half-empty": ["评分","星星","半星"],
	"fa-star-half-full": ["评分","星星","半星"],
	"fa-star-half-o": ["评分","黑星","星星"],
	"fa-star-o": ["评分","白星","星星","空心星星"],
	"fa-steam": [],
	"fa-steam-square": [],
	"fa-step-backward": [],
	"fa-step-forward": [],
	"fa-sticky-note": [],
	"fa-sticky-note-o": "fa-sticky-note",
	"fa-stop": ["暂停","方块","黑色"],
	"fa-street-view": ["街景"],
	"fa-strikethrough": [],
	"fa-stumbleupon": [],
	"fa-stumbleupon-circle": [],
	"fa-subscript": [],
	"fa-subway": ["火车", "旅行"],
	"fa-suitcase": [],
	"fa-sun-o": [],
	"fa-superscript": [],
	"fa-support": ["帮助", "救援"],
	"fa-table": ["表格", "数据"],
	"fa-tablet": ["平板"],
	"fa-tachometer": ["仪表盘", "控制台", "速率表"],
	"fa-tag": ["标签","提示"],
	"fa-tags": ["标签","提示"],
	"fa-tasks": [],
	"fa-taxi": ["车","交通","出租车","taxi"],
	"fa-television": ["电视","屏幕"],
	"fa-tencent-weibo": [],
	"fa-terminal": ["命令行","终端"],
	"fa-text-height": [],
	"fa-text-width": [],
	"fa-th": [],
	"fa-th-large": [],
	"fa-th-list": ["列表","菜单"],
	"fa-thumb-tack": ["图钉","标记","tag"],
	"fa-thumbs-down": ["踩","倒喝彩"],
	"fa-thumbs-o-down": ["踩","倒喝彩"],
	"fa-thumbs-o-up": ["赞","鼓励"],
	"fa-thumbs-up": ["赞","鼓励"],
	"fa-ticket": [],
	"fa-times": ["关闭","错误","提示","警告","交叉"],
	"fa-times-circle": ["关闭","错误","提示","警告","交叉"],
	"fa-times-circle-o": ["\t关闭","错误","提示","警告","交叉"],
	"fa-tint": [],
	"fa-toggle-down": [],
	"fa-toggle-left": [],
	"fa-toggle-off": [],
	"fa-toggle-on": [],
	"fa-toggle-right": [],
	"fa-toggle-up": [],
	"fa-trademark": ["商标","TM"],
	"fa-train": [],
	"fa-transgender": [],
	"fa-transgender-alt": [],
	"fa-trash": ["回收站","删除","垃圾"],
	"fa-trash-o": ["回收站","删除","垃圾"],
	"fa-tree": ["树木","森林","资源"],
	"fa-trello": [],
	"fa-tripadvisor": [],
	"fa-trophy": ["奖杯","冠军"],
	"fa-truck": ["货车","交通","车辆"],
	"fa-try": [],
	"fa-tty": ["电话","tty","文字转语音"],
	"fa-tumblr": [],
	"fa-tumblr-square": [],
	"fa-turkish-lira": [],
	"fa-tv": ["电视","屏幕"],
	"fa-twitch": [],
	"fa-twitter": [],
	"fa-twitter-square": [],
	"fa-umbrella": ["雨伞"],
	"fa-underline": ["下划线"],
	"fa-undo": ["撤销","恢复","旋转"],
	"fa-university": ["建筑","大学","法院"],
	"fa-unlink": ["链接断开","删除","问题","错误"],
	"fa-unlock": ["锁","解锁"],
	"fa-unlock-alt": ["锁","解锁"],
	"fa-unsorted": ["排序","上下"],
	"fa-upload": ["上传","磁盘"],
	"fa-usd": [],
	"fa-user": ["用户","人"],
	"fa-user-plus": ["添加用户","人"],
	"fa-user-secret": ["间谍","隐私","保密"],
	"fa-user-times": ["删除用户"],
	"fa-users": ["用户组","多个用户","群体","人","人们"],
	"fa-venus": ["女性"],
	"fa-venus-double": [],
	"fa-venus-mars": [],
	"fa-viacoin": [],
	"fa-video-camera": [],
	"fa-vimeo": [],
	"fa-vimeo-square": [],
	"fa-vine": [],
	"fa-vk": [],
	"fa-volume-down": ["音量","喇叭","一格音量","减小音量"],
	"fa-volume-off": ["音量","喇叭","静音"],
	"fa-volume-up": ["音量","喇叭","三格音量","加大音量"],
	"fa-warning": [],
	"fa-wechat": "fa-weixin",
	"fa-weibo": ["新浪微博"],
	"fa-weixin": ["微信"],
	"fa-whatsapp": ["Whatsapp","电话","留言","对话","通话"],
	"fa-wheelchair": [],
	"fa-wifi": [],
	"fa-wikipedia-w": ["Wiki","维基","百科"],
	"fa-windows": ["Windows"],
	"fa-won": [],
	"fa-wordpress": ["Wordpress","博客"],
	"fa-wrench": ["扳手", "配置"],
	"fa-xing": [],
	"fa-xing-square": [],
	"fa-y-combinator": [],
	"fa-y-combinator-square": "fa-hacker-news",
	"fa-yahoo": [],
	"fa-yc": "fa-y-combinator",
	"fa-yc-square": "fa-hacker-news",
	"fa-yelp": [],
	"fa-yen": [],
	"fa-youtube": [],
	"fa-youtube-play": [],
	"fa-youtube-square": []
}